### ISSUE TITLE
[Bug]: Links not working, commands outputs errors,etc

### ISSUE THREAD

**Issue by adodon2go** [project-zot/project-zot.github.io#117]
### zot version

v1.4.3

### Describe the bug

1.  In this section: https://zotregistry.io/v1.4.3/admin-guide/admin-getting-started/#example-deploying-with-a-container-manager

The command is wrong and must be replaced:
`
midgard@yggdrasil:~/work/github.com/project-zot/project-zot.github.io$ podman run -p 5000:5000 ghcr.io/project-zot/zot-linux-amd64-minimal:latest
Trying to pull ghcr.io/project-zot/zot-linux-amd64-minimal:latest...
Error: initializing source docker://ghcr.io/project-zot/zot-linux-amd64-minimal:latest: Requesting bear token: invalid status code from registry 403 (Forbidden)
`
Image name should be replaced from  _ghcr.io/project-zot/zot-linux-amd64-minimal:latest_ to  **ghcr.io/project-zot/zot-minimal-linux-amd64:lates**t

2. In this section https://zotregistry.io/v1.4.3/developer-guide/extensions-dev/#guidelines-for-developing-new-extensions we have a link to extension-lint-disable.go which point wrongly here:https://github.com/project-zot/zot/blob/main/pkg/extensions/lint/lint-disabled.go.
Correct link should be this one https://github.com/project-zot/zot/blob/main/pkg/extensions/lint/lint_disabled.go

3. Folowin the guidence from this page https://zotregistry.io/v1.4.3/developer-guide/onboarding/#supported-developer-platforms and running zot as sugested by the command here https://zotregistry.io/v1.4.3/developer-guide/onboarding/#running-zot I get a panic as below. 
I suggest changing the configuration file to minimal:
`bin/zot-linux-amd64 serve examples/config-minimal.json`

The current panic message:
```
midgard@joro:~/work/github.com/adodon2go/zot$  bin/zot-linux-amd64 serve examples/config-example.json
panic: open test/data/htpasswd: no such file or directory

goroutine 1 [running]:
zotregistry.io/zot/pkg/api.(*AuthnMiddleware).TryAuthnHandlers(0xc0012ce920, 0xc000fb7600)
	zotregistry.io/zot/pkg/api/authn.go:318 +0xcd6
zotregistry.io/zot/pkg/api.AuthHandler(0xc000fb7600)
	zotregistry.io/zot/pkg/api/authn.go:63 +0x65
zotregistry.io/zot/pkg/api.(*RouteHandler).SetupRoutes(0xc000135dd8)
	zotregistry.io/zot/pkg/api/routes.go:67 +0x30
zotregistry.io/zot/pkg/api.NewRouteHandler(...)
	zotregistry.io/zot/pkg/api/routes.go:60
zotregistry.io/zot/pkg/api.(*Controller).Run(0xc000fb7600, {0x562507d4ca68?, 0xc0025d29b0?})
	zotregistry.io/zot/pkg/api/controller.go:129 +0x51b
zotregistry.io/zot/pkg/cli.NewServerRootCmd.newServeCmd.func2(0xc000fb6b00?, {0xc000abc920, 0x1, 0x562505032d26?})
	zotregistry.io/zot/pkg/cli/root.go:69 +0xc8
github.com/spf13/cobra.(*Command).execute(0xc000f8c600, {0xc000abc8e0, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f8c300)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.main()
	zotregistry.io/zot/cmd/zot/main.go:10 +0x18
```

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by mbshields** [comment]
Fixed for v1.4.3 in PR #118
